# Generated by Django 3.1 on 2020-08-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialDemoModelPersonalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=20)),
                ('Address', models.CharField(default='', max_length=200)),
                ('Age', models.IntegerField(default='')),
            ],
        ),
    ]
